using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace Dreamwork{
public class class_dict : MonoBehaviour
{
	public static Dictionary<int, string> id2class = new Dictionary<int, string>()
	{
	  {0 , "alarm clock"},
	  {1 , "ant"},
	  {2 , "anvil"},
	  {3 , "apple"},
	  {4 , "axe"},
	  {5 , "backpack"},
	  {6 , "bandage"},
	  {7 , "baseball bat"},
	  {8 , "basket"},
	  {9 , "bed"},
	  {10 , "bee"},
	  {11 , "bench"},
	  {12 , "binoculars"},
	  {13 , "bird"},
	  {14 , "book"},
	  {15 , "boomerang"},
	  {16 , "brain"},
	  {17 , "bridge"},
	  {18 , "broom"},
	  {19 , "bucket"},
	  {20 , "butterfly"},
	  {21 , "calculator"},
	  {22 , "calendar"},
	  {23 , "camera"},
	  {24 , "campfire"},
	  {25 , "candle"},
	  {26 , "cannon"},
	  {27 , "canoe"},
	  {28 , "carrot"},
	  {29 , "cat"},
	  {30 , "ceiling fan"},
	  {31 , "cell phone"},
	  {32 , "chair"},
	  {33 , "chandelier"},
	  {34 , "clock"},
	  {35 , "cloud"},
	  {36 , "compass"},
	  {37 , "computer"},
	  {38 , "cow"},
	  {39 , "cup"},
	  {40 , "diamond"},
	  {41 , "diving board"},
	  {42 , "dog"},
	  {43 , "donut"},
	  {44 , "door"},
	  {45 , "dragon"},
	  {46 , "drill"},
	  {47 , "drums"},
	  {48 , "dumbbell"},
	  {49 , "ear"},
	  {50 , "envelope"},
	  {51 , "eraser"},
	  {52 , "eye"},
	  {53 , "eyeglasses"},
	  {54 , "fan"},
	  {55 , "feather"},
	  {56 , "fence"},
	  {57 , "fire hydrant"},
	  {58 , "fireplace"},
	  {59 , "fish"},
	  {60 , "flashlight"},
	  {61 , "floor lamp"},
	  {62 , "flower"},
	  {63 , "foot"},
	  {64 , "fork"},
	  {65 , "frying pan"},
	  {66 , "garden hose"},
	  {67 , "hammer"},
	  {68 , "hand"},
	  {69 , "hat"},
	  {70 , "helmet"},
	  {71 , "hot air balloon"},
	  {72 , "hourglass"},
	  {73 , "hurricane"},
	  {74 , "key"},
	  {75 , "knife"},
	  {76 , "ladder"},
	  {77 , "lantern"},
	  {78 , "light bulb"},
	  {79 , "lighter"},
	  {80 , "lightning"},
	  {81 , "line"},
	  {82 , "lion"},
	  {83 , "lollipop"},
	  {84 , "map"},
	  {85 , "marker"},
	  {86 , "matches"},
	  {87 , "megaphone"},
	  {88 , "microphone"},
	  {89 , "moon"},
	  {90 , "moustache"},
	  {91 , "mouth"},
	  {92 , "nail"},
	  {93 , "nose"},
	  {94 , "oven"},
	  {95 , "paint can"},
	  {96 , "paintbrush"},
	  {97 , "paper clip"},
	  {98 , "parachute"},
	  {99 , "pillow"},
	  {100 , "pizza"},
	  {101 , "pliers"},
	  {102 , "pond"},
	  {103 , "pool"},
	  {104 , "power outlet"},
	  {105 , "radio"},
	  {106 , "rain"},
	  {107 , "rainbow"},
	  {108 , "rake"},
	  {109 , "remote control"},
	  {110 , "rifle"},
	  {111 , "river"},
	  {112 , "sailboat"},
	  {113 , "saw"},
	  {114 , "scissors"},
	  {115 , "screwdriver"},
	  {116 , "shovel"},
	  {117 , "skull"},
	  {118 , "sleeping bag"},
	  {119 , "snorkel"},
	  {120 , "snowman"},
	  {121 , "spoon"},
	  {122 , "stairs"},
	  {123 , "star"},
	  {124 , "stop sign"},
	  {125 , "stove"},
	  {126 , "suitcase"},
	  {127 , "sun"},
	  {128 , "sword"},
	  {129 , "teddy-bear"},
	  {130 , "telephone"},
	  {131 , "tent"},
	  {132 , "tornado"},
	  {133 , "traffic light"},
	  {134 , "tree"},
	  {135 , "umbrella"},
	  {136 , "wheel"},
	  {137 , "wristwatch"}
	};
}
}
